// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_z-wSQmCIUXpYLNyM_5wq7ZReOTFEC0',
    appId: '1:839083180340:web:338cdba81ed67d77be2561',
    messagingSenderId: '839083180340',
    projectId: 'testcli-6312a',
    authDomain: 'testcli-6312a.firebaseapp.com',
    storageBucket: 'testcli-6312a.appspot.com',
    measurementId: 'G-SXLYGWGL16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4fo5vywhXrdORJsTJtKJu1vYkkuactc',
    appId: '1:839083180340:android:894d06747f895f97be2561',
    messagingSenderId: '839083180340',
    projectId: 'testcli-6312a',
    storageBucket: 'testcli-6312a.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0YfbGXQ7rVL-o83TO0bp2ex0ivld5olU',
    appId: '1:839083180340:ios:58dff1004c765f8dbe2561',
    messagingSenderId: '839083180340',
    projectId: 'testcli-6312a',
    storageBucket: 'testcli-6312a.appspot.com',
    iosBundleId: 'com.example.fireBaseNewProject.RunnerTests',
  );
}
